services:
- type: web
  name: moncock-website
  runtime: static
  buildCommand: yarn; yarn build
  staticPublishPath: out
  pullRequestPreviewsEnabled: true     # optional
  envVars:
  - key: NODE_ENV
    value: production