import AppProvider from '@contexts/appProvider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Moncock',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="th">
            <body>
                <AppProvider>{children}</AppProvider>
            </body>
        </html>
    );
}
